import SideBar from "@/components/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GroupLayout({ children }) {
  return (
    <main className="flex">
      <SideBar />
      {children}
    </main>
  );
}
