import SideBar from "@/components/SideBar";
import TopNavbar from "@/components/TopNavbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GroupLayout({ children }) {
  return (
    <main className="flex min-h-screen">
      <SideBar />
      <div className="ml-[250px] flex flex-1 flex-col min-w-0">
        <TopNavbar />
        {children}
      </div>
    </main>
  );
}
