import {Poppins} from 'next/font/google';
import './globals.css';
import {Providers} from '@/redux/provider';
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { FollowUpProvider } from "@/context/FollowUpProvider";

const poppins = Poppins({
  weight: ['700','600', '400'],
  subsets: ['latin'],
});
export const metadata = {
  title: 'Sales Dashboard | 10000Coders',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <FollowUpProvider>
            <ToastContainer />
            {children}
          </FollowUpProvider>
        </Providers>
      </body>
    </html>
  );
}
